### ISSUE TITLE
vmware error

### ISSUE THREAD

**Issue by mudebug77** [wiresock/ndisapi#14]
我想实现一个nat 在vmware中 类似 [pcap2cosy](https://github.com/zhxie/pcap2socks)
在pcap中可以获取到 网卡列表
在Windows Packet Filter 3.2.32.1 x64 无法获取到网卡列表
pcap :
![image](https://user-images.githubusercontent.com/34656102/172029806-e4d7d43a-9501-4367-8e05-b15f94e9d484.png)

ndis
![image](https://user-images.githubusercontent.com/34656102/172029831-4ad0582a-4b91-49fd-bdfe-666718d3520d.png)

translate.google :
I want to implement a nat in vmware similar to pcap2socks
The list of network cards can be obtained in pcap
Unable to get network card list in Windows Packet Filter 3.2.32.1 x64

**Comment by wiresock** [comment]
I can see from your screenshot that the Windows Packet Filter is bound to 5 network interfaces. I think it's confusing to you that it's not tied to VMWare network adapters. However, this is expected behavior. The standard Windows Packet Filter does not bind to certain types of virtual network adapters, including VMWare or WinTun. This is relatively easy to fix though by changing the driver's INF file as it is described here: https://www.ntkernel.com/forums/topic/wintun-support/

Also, for example, custom Windows Packet Filter builds used in https://wiresock.net project do bind to WinTun.

**Comment by mudebug77** [comment]
thanks
